name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  determine-changes:
    runs-on: ubuntu-22.04
    outputs:
      tests: ${{ steps.filter.outputs.tests }}
      vendoring: ${{ steps.filter.outputs.vendoring }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            vendoring:
              # Anything that's touching "vendored code"
              - "src/pip/_vendor/**"
              - "pyproject.toml"
              - "noxfile.py"
            tests:
              # Anything that's touching code-related stuff
              - ".github/workflows/ci.yml"
              - "src/**"
              - "tests/**"
              - "noxfile.py"
              # The test suite should also run when cutting a release
              # (which is the only time this file is modified).
              - "NEWS.rst"
        if: github.event_name == 'pull_request'

  packaging:
    name: packaging
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

  tests-windows:
    name: tests / ${{ matrix.python }} / ${{ matrix.os }} / ${{ matrix.group.number }}
    runs-on: ${{ matrix.os }}-latest

    needs: [packaging, determine-changes]

    strategy:
      matrix:
        os: [Windows]
        python:
          # NOTE: don't forget to update middle versions below!
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        group:
          - { number: 1, pytest-filter: "not test_install" }
          - { number: 2, pytest-filter: "test_install" }
        scheduled:
          - ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        exclude:
          # Only run Windows CI across all Python versions during a scheduled run.
          - { python: "3.9", scheduled: false }
          - { python: "3.10", scheduled: false }
          - { python: "3.11", scheduled: false }
          - { python: "3.12", scheduled: false }

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true

      - name: Debug
        run: |
          echo Python] "${{ matrix.python }}"
          echo Group] "${{ matrix.group.number }}"
          echo Pytest] "${{ matrix.group.pytest-filter }}"
          echo Schedule] "${{ matrix.scheduled }}"
