name: nox-install

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  packaging:
    # env:
    #   PYTHONPROFILEIMPORTTIME: yes
    name: ${{ matrix.os }} / ${{ matrix.method }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        method: ["python -m pip", "pip"]

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install nox
        if: matrix.method == 'pip'

      - run: python -m pip install nox
        if: matrix.method == 'python -m pip'
