name: nox-install

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  packaging:
    name: packaging / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python -Ximporttime -m pip install nox
      - run: python -Ximporttime -m pip uninstall nox -y
      - run: python -Ximporttime -m pip install nox
