name: nox-install

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  packaging:
    # env:
    #   PYTHONPROFILEIMPORTTIME: yes
    env:
      PYTHONPYCACHEPREFIX: D:\custom_pycache
    name: ${{ matrix.os }} / ${{ matrix.method }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        method: ["python -m pip", "pip"]

    steps:
      - run: mkdir D:\custom_pycache
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # - run: pipx run nox --help

      - run: pip install nox
        if: matrix.method == 'pip'

      - run: python -m pip install nox
        if: matrix.method == 'python -m pip'
